config/routes.rb
Rails.application.routes.draw do
  resources :learn_favorites
  resources :learn_images
  resources :learn_comments
  resources :post_images
  resources :post_likes
  resources :post_comments
  resources :disscuss_comments
  resources :learns
  resources :posts
  resources :discusses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discuss.rb
class Discuss < ApplicationRecord
end

app/models/disscuss_comment.rb
class DisscussComment < ApplicationRecord
    belongs_to :discuss
end

app/models/learn.rb
class Learn < ApplicationRecord
end

app/models/learn_comment.rb
class LearnComment < ApplicationRecord
    belongs_to :learn
end

app/models/learn_favorite.rb
class LearnFavorite < ApplicationRecord
    belongs_to :learn
end

app/models/learn_image.rb
class LearnImage < ApplicationRecord
    belongs_to :learn
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :post
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :post
end

app/controllers/disscuss_comments_controller.rb
class DisscussCommentsController < ApplicationController
  before_action :set_disscuss_comment, only: %i[ show edit update destroy ]

  # GET /disscuss_comments or /disscuss_comments.json
  def index
    @disscuss_comments = DisscussComment.all
  end

  # GET /disscuss_comments/1 or /disscuss_comments/1.json
  def show
  end

  # GET /disscuss_comments/new
  def new
    @disscuss_comment = DisscussComment.new
  end

  # GET /disscuss_comments/1/edit
  def edit
  end

  # POST /disscuss_comments or /disscuss_comments.json
  def create
    @disscuss_comment = DisscussComment.new(disscuss_comment_params)

    respond_to do |format|
      if @disscuss_comment.save
        format.html { redirect_to disscuss_comment_url(@disscuss_comment), notice: "Disscuss comment was successfully created." }
        format.json { render :show, status: :created, location: @disscuss_comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @disscuss_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disscuss_comments/1 or /disscuss_comments/1.json
  def update
    respond_to do |format|
      if @disscuss_comment.update(disscuss_comment_params)
        format.html { redirect_to disscuss_comment_url(@disscuss_comment), notice: "Disscuss comment was successfully updated." }
        format.json { render :show, status: :ok, location: @disscuss_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @disscuss_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disscuss_comments/1 or /disscuss_comments/1.json
  def destroy
    @disscuss_comment.destroy

    respond_to do |format|
      format.html { redirect_to disscuss_comments_url, notice: "Disscuss comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disscuss_comment
      @disscuss_comment = DisscussComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def disscuss_comment_params
      params.require(:disscuss_comment).permit(:discuss_id, :discuss_comment, :user_id)
    end
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController
  before_action :set_learn, only: %i[ show edit update destroy ]

  # GET /learns or /learns.json
  def index
    @learns = Learn.all
  end

  # GET /learns/1 or /learns/1.json
  def show
  end

  # GET /learns/new
  def new
    @learn = Learn.new
  end

  # GET /learns/1/edit
  def edit
  end

  # POST /learns or /learns.json
  def create
    @learn = Learn.new(learn_params)

    respond_to do |format|
      if @learn.save
        format.html { redirect_to learn_url(@learn), notice: "Learn was successfully created." }
        format.json { render :show, status: :created, location: @learn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learns/1 or /learns/1.json
  def update
    respond_to do |format|
      if @learn.update(learn_params)
        format.html { redirect_to learn_url(@learn), notice: "Learn was successfully updated." }
        format.json { render :show, status: :ok, location: @learn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learns/1 or /learns/1.json
  def destroy
    @learn.destroy

    respond_to do |format|
      format.html { redirect_to learns_url, notice: "Learn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learn
      @learn = Learn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def learn_params
      params.require(:learn).permit(:user_id, :title, :article, :comment, :image, :favorite)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :content, :image, :like, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discusses_helper.rb
module DiscussesHelper
end

app/helpers/disscuss_comments_helper.rb
module DisscussCommentsHelper
end

app/helpers/learn_images_helper.rb
module LearnImagesHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/disscuss_comments/_disscuss_comment.html.erb
<div id="<%= dom_id disscuss_comment %>">
  <p>
    <strong>Discuss:</strong>
    <%= disscuss_comment.discuss_id %>
  </p>

  <p>
    <strong>Discuss comment:</strong>
    <%= disscuss_comment.discuss_comment %>
  </p>

  <p>
    <strong>User:</strong>
    <%= disscuss_comment.user_id %>
  </p>

</div>

app/views/disscuss_comments/_form.html.erb
<%= form_with(model: disscuss_comment) do |form| %>
  <% if disscuss_comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(disscuss_comment.errors.count, "error") %> prohibited this disscuss_comment from being saved:</h2>

      <ul>
        <% disscuss_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :discuss_id, style: "display: block" %>
    <%= form.number_field :discuss_id %>
  </div>

  <div>
    <%= form.label :discuss_comment, style: "display: block" %>
    <%= form.text_area :discuss_comment %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/disscuss_comments/edit.html.erb
<h1>Editing disscuss comment</h1>

<%= render "form", disscuss_comment: @disscuss_comment %>

<br>

<div>
  <%= link_to "Show this disscuss comment", @disscuss_comment %> |
  <%= link_to "Back to disscuss comments", disscuss_comments_path %>
</div>

app/views/disscuss_comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Disscuss comments</h1>

<div id="disscuss_comments">
  <% @disscuss_comments.each do |disscuss_comment| %>
    <%= render disscuss_comment %>
    <p>
      <%= link_to "Show this disscuss comment", disscuss_comment %>
    </p>
  <% end %>
</div>

<%= link_to "New disscuss comment", new_disscuss_comment_path %>

app/views/disscuss_comments/new.html.erb
<h1>New disscuss comment</h1>

<%= render "form", disscuss_comment: @disscuss_comment %>

<br>

<div>
  <%= link_to "Back to disscuss comments", disscuss_comments_path %>
</div>

app/views/disscuss_comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @disscuss_comment %>

<div>
  <%= link_to "Edit this disscuss comment", edit_disscuss_comment_path(@disscuss_comment) %> |
  <%= link_to "Back to disscuss comments", disscuss_comments_path %>

  <%= button_to "Destroy this disscuss comment", @disscuss_comment, method: :delete %>
</div>