config/routes.rb
Rails.application.routes.draw do
  resources :learn_favorites
  resources :learn_images
  resources :learn_comments
  resources :post_images
  resources :post_likes
  resources :post_comments
  resources :disscuss_comments
  resources :learns
  resources :posts
  resources :discusses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discuss.rb
class Discuss < ApplicationRecord
end

app/models/disscuss_comment.rb
class DisscussComment < ApplicationRecord
    belongs_to :discuss
end

app/models/learn.rb
class Learn < ApplicationRecord
end

app/models/learn_comment.rb
class LearnComment < ApplicationRecord
    belongs_to :learn
end

app/models/learn_favorite.rb
class LearnFavorite < ApplicationRecord
    belongs_to :learn
end

app/models/learn_image.rb
class LearnImage < ApplicationRecord
    belongs_to :learn
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :post
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :post
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController
  before_action :set_learn, only: %i[ show edit update destroy ]

  # GET /learns or /learns.json
  def index
    @learns = Learn.all
  end

  # GET /learns/1 or /learns/1.json
  def show
  end

  # GET /learns/new
  def new
    @learn = Learn.new
  end

  # GET /learns/1/edit
  def edit
  end

  # POST /learns or /learns.json
  def create
    @learn = Learn.new(learn_params)

    respond_to do |format|
      if @learn.save
        format.html { redirect_to learn_url(@learn), notice: "Learn was successfully created." }
        format.json { render :show, status: :created, location: @learn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learns/1 or /learns/1.json
  def update
    respond_to do |format|
      if @learn.update(learn_params)
        format.html { redirect_to learn_url(@learn), notice: "Learn was successfully updated." }
        format.json { render :show, status: :ok, location: @learn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learns/1 or /learns/1.json
  def destroy
    @learn.destroy

    respond_to do |format|
      format.html { redirect_to learns_url, notice: "Learn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learn
      @learn = Learn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def learn_params
      params.require(:learn).permit(:user_id, :title, :article, :comment, :image, :favorite)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :content, :image, :like, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discusses_helper.rb
module DiscussesHelper
end

app/helpers/learn_comments_helper.rb
module LearnCommentsHelper
end

app/helpers/learn_favorites_helper.rb
module LearnFavoritesHelper
end

app/helpers/learn_images_helper.rb
module LearnImagesHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/learns/_form.html.erb
<%= form_with(model: learn) do |form| %>
  <% if learn.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(learn.errors.count, "error") %> prohibited this learn from being saved:</h2>

      <ul>
        <% learn.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :article, style: "display: block" %>
    <%= form.text_area :article %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.number_field :image %>
  </div>

  <div>
    <%= form.label :favorite, style: "display: block" %>
    <%= form.number_field :favorite %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/learns/_learn.html.erb
<div id="<%= dom_id learn %>">
  <p>
    <strong>User:</strong>
    <%= learn.user_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= learn.title %>
  </p>

  <p>
    <strong>Article:</strong>
    <%= learn.article %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= learn.comment %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= learn.image %>
  </p>

  <p>
    <strong>Favorite:</strong>
    <%= learn.favorite %>
  </p>

</div>

app/views/learns/edit.html.erb
<h1>Editing learn</h1>

<%= render "form", learn: @learn %>

<br>

<div>
  <%= link_to "Show this learn", @learn %> |
  <%= link_to "Back to learns", learns_path %>
</div>

app/views/learns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Learns</h1>

<div id="learns">
  <% @learns.each do |learn| %>
    <%= render learn %>
    <p>
      <%= link_to "Show this learn", learn %>
    </p>
  <% end %>
</div>

<%= link_to "New learn", new_learn_path %>

app/views/learns/new.html.erb
<h1>New learn</h1>

<%= render "form", learn: @learn %>

<br>

<div>
  <%= link_to "Back to learns", learns_path %>
</div>

app/views/learns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @learn %>

<div>
  <%= link_to "Edit this learn", edit_learn_path(@learn) %> |
  <%= link_to "Back to learns", learns_path %>

  <%= button_to "Destroy this learn", @learn, method: :delete %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.number_field :image %>
  </div>

  <div>
    <%= form.label :like, style: "display: block" %>
    <%= form.number_field :like %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_field :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= post.image %>
  </p>

  <p>
    <strong>Like:</strong>
    <%= post.like %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= post.comment %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>