config/routes.rb
Rails.application.routes.draw do
  resources :learn_favorites
  resources :learn_images
  resources :learn_comments
  resources :post_images
  resources :post_likes
  resources :post_comments
  resources :disscuss_comments
  resources :learns
  resources :posts
  resources :discusses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discuss.rb
class Discuss < ApplicationRecord
end

app/models/disscuss_comment.rb
class DisscussComment < ApplicationRecord
    belongs_to :discuss
end

app/models/learn.rb
class Learn < ApplicationRecord
end

app/models/learn_comment.rb
class LearnComment < ApplicationRecord
    belongs_to :learn
end

app/models/learn_favorite.rb
class LearnFavorite < ApplicationRecord
    belongs_to :learn
end

app/models/learn_image.rb
class LearnImage < ApplicationRecord
    belongs_to :learn
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :post
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :post
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController
  before_action :set_learn, only: %i[ show edit update destroy ]

  # GET /learns or /learns.json
  def index
    @learns = Learn.all
  end

  # GET /learns/1 or /learns/1.json
  def show
  end

  # GET /learns/new
  def new
    @learn = Learn.new
  end

  # GET /learns/1/edit
  def edit
  end

  # POST /learns or /learns.json
  def create
    @learn = Learn.new(learn_params)

    respond_to do |format|
      if @learn.save
        format.html { redirect_to learn_url(@learn), notice: "Learn was successfully created." }
        format.json { render :show, status: :created, location: @learn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learns/1 or /learns/1.json
  def update
    respond_to do |format|
      if @learn.update(learn_params)
        format.html { redirect_to learn_url(@learn), notice: "Learn was successfully updated." }
        format.json { render :show, status: :ok, location: @learn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learns/1 or /learns/1.json
  def destroy
    @learn.destroy

    respond_to do |format|
      format.html { redirect_to learns_url, notice: "Learn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learn
      @learn = Learn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def learn_params
      params.require(:learn).permit(:user_id, :title, :article, :comment, :image, :favorite)
    end
end

app/controllers/post_likes_controller.rb
class PostLikesController < ApplicationController
  before_action :set_post_like, only: %i[ show edit update destroy ]

  # GET /post_likes or /post_likes.json
  def index
    @post_likes = PostLike.all
  end

  # GET /post_likes/1 or /post_likes/1.json
  def show
  end

  # GET /post_likes/new
  def new
    @post_like = PostLike.new
  end

  # GET /post_likes/1/edit
  def edit
  end

  # POST /post_likes or /post_likes.json
  def create
    @post_like = PostLike.new(post_like_params)

    respond_to do |format|
      if @post_like.save
        format.html { redirect_to post_like_url(@post_like), notice: "Post like was successfully created." }
        format.json { render :show, status: :created, location: @post_like }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_likes/1 or /post_likes/1.json
  def update
    respond_to do |format|
      if @post_like.update(post_like_params)
        format.html { redirect_to post_like_url(@post_like), notice: "Post like was successfully updated." }
        format.json { render :show, status: :ok, location: @post_like }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_likes/1 or /post_likes/1.json
  def destroy
    @post_like.destroy

    respond_to do |format|
      format.html { redirect_to post_likes_url, notice: "Post like was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_like
      @post_like = PostLike.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_like_params
      params.require(:post_like).permit(:post_id, :post_like, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :content, :image, :like, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discusses_helper.rb
module DiscussesHelper
end

app/helpers/learn_comments_helper.rb
module LearnCommentsHelper
end

app/helpers/learn_images_helper.rb
module LearnImagesHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/post_likes/_form.html.erb
<%= form_with(model: post_like) do |form| %>
  <% if post_like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post_like.errors.count, "error") %> prohibited this post_like from being saved:</h2>

      <ul>
        <% post_like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.number_field :post_id %>
  </div>

  <div>
    <%= form.label :post_like, style: "display: block" %>
    <%= form.number_field :post_like %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/post_likes/_post_like.html.erb
<div id="<%= dom_id post_like %>">
  <p>
    <strong>Post:</strong>
    <%= post_like.post_id %>
  </p>

  <p>
    <strong>Post like:</strong>
    <%= post_like.post_like %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post_like.user_id %>
  </p>

</div>

app/views/post_likes/edit.html.erb
<h1>Editing post like</h1>

<%= render "form", post_like: @post_like %>

<br>

<div>
  <%= link_to "Show this post like", @post_like %> |
  <%= link_to "Back to post likes", post_likes_path %>
</div>

app/views/post_likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Post likes</h1>

<div id="post_likes">
  <% @post_likes.each do |post_like| %>
    <%= render post_like %>
    <p>
      <%= link_to "Show this post like", post_like %>
    </p>
  <% end %>
</div>

<%= link_to "New post like", new_post_like_path %>

app/views/post_likes/new.html.erb
<h1>New post like</h1>

<%= render "form", post_like: @post_like %>

<br>

<div>
  <%= link_to "Back to post likes", post_likes_path %>
</div>

app/views/post_likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post_like %>

<div>
  <%= link_to "Edit this post like", edit_post_like_path(@post_like) %> |
  <%= link_to "Back to post likes", post_likes_path %>

  <%= button_to "Destroy this post like", @post_like, method: :delete %>
</div>