config/routes.rb
Rails.application.routes.draw do
  resources :learn_favorites
  resources :learn_images
  resources :learn_comments
  resources :post_images
  resources :post_likes
  resources :post_comments
  resources :disscuss_comments
  resources :learns
  resources :posts
  resources :discusses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discuss.rb
class Discuss < ApplicationRecord
end

app/models/disscuss_comment.rb
class DisscussComment < ApplicationRecord
    belongs_to :discuss
end

app/models/learn.rb
class Learn < ApplicationRecord
end

app/models/learn_comment.rb
class LearnComment < ApplicationRecord
    belongs_to :learn
end

app/models/learn_favorite.rb
class LearnFavorite < ApplicationRecord
    belongs_to :learn
end

app/models/learn_image.rb
class LearnImage < ApplicationRecord
    belongs_to :learn
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :post
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :post
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController
  before_action :set_learn, only: %i[ show edit update destroy ]

  # GET /learns or /learns.json
  def index
    @learns = Learn.all
  end

  # GET /learns/1 or /learns/1.json
  def show
  end

  # GET /learns/new
  def new
    @learn = Learn.new
  end

  # GET /learns/1/edit
  def edit
  end

  # POST /learns or /learns.json
  def create
    @learn = Learn.new(learn_params)

    respond_to do |format|
      if @learn.save
        format.html { redirect_to learn_url(@learn), notice: "Learn was successfully created." }
        format.json { render :show, status: :created, location: @learn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learns/1 or /learns/1.json
  def update
    respond_to do |format|
      if @learn.update(learn_params)
        format.html { redirect_to learn_url(@learn), notice: "Learn was successfully updated." }
        format.json { render :show, status: :ok, location: @learn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learns/1 or /learns/1.json
  def destroy
    @learn.destroy

    respond_to do |format|
      format.html { redirect_to learns_url, notice: "Learn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learn
      @learn = Learn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def learn_params
      params.require(:learn).permit(:user_id, :title, :article, :comment, :image, :favorite)
    end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :set_post_image, only: %i[ show edit update destroy ]

  # GET /post_images or /post_images.json
  def index
    @post_images = PostImage.all
  end

  # GET /post_images/1 or /post_images/1.json
  def show
  end

  # GET /post_images/new
  def new
    @post_image = PostImage.new
  end

  # GET /post_images/1/edit
  def edit
  end

  # POST /post_images or /post_images.json
  def create
    @post_image = PostImage.new(post_image_params)

    respond_to do |format|
      if @post_image.save
        format.html { redirect_to post_image_url(@post_image), notice: "Post image was successfully created." }
        format.json { render :show, status: :created, location: @post_image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_images/1 or /post_images/1.json
  def update
    respond_to do |format|
      if @post_image.update(post_image_params)
        format.html { redirect_to post_image_url(@post_image), notice: "Post image was successfully updated." }
        format.json { render :show, status: :ok, location: @post_image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_images/1 or /post_images/1.json
  def destroy
    @post_image.destroy

    respond_to do |format|
      format.html { redirect_to post_images_url, notice: "Post image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_image_params
      params.require(:post_image).permit(:post_id, :post_image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :content, :image, :like, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discusses_helper.rb
module DiscussesHelper
end

app/helpers/learn_comments_helper.rb
module LearnCommentsHelper
end

app/helpers/learn_images_helper.rb
module LearnImagesHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/post_images/_form.html.erb
<%= form_with(model: post_image) do |form| %>
  <% if post_image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post_image.errors.count, "error") %> prohibited this post_image from being saved:</h2>

      <ul>
        <% post_image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.number_field :post_id %>
  </div>

  <div>
    <%= form.label :post_image, style: "display: block" %>
    <%= form.number_field :post_image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/post_images/_post_image.html.erb
<div id="<%= dom_id post_image %>">
  <p>
    <strong>Post:</strong>
    <%= post_image.post_id %>
  </p>

  <p>
    <strong>Post image:</strong>
    <%= post_image.post_image %>
  </p>

</div>

app/views/post_images/edit.html.erb
<h1>Editing post image</h1>

<%= render "form", post_image: @post_image %>

<br>

<div>
  <%= link_to "Show this post image", @post_image %> |
  <%= link_to "Back to post images", post_images_path %>
</div>

app/views/post_images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Post images</h1>

<div id="post_images">
  <% @post_images.each do |post_image| %>
    <%= render post_image %>
    <p>
      <%= link_to "Show this post image", post_image %>
    </p>
  <% end %>
</div>

<%= link_to "New post image", new_post_image_path %>

app/views/post_images/new.html.erb
<h1>New post image</h1>

<%= render "form", post_image: @post_image %>

<br>

<div>
  <%= link_to "Back to post images", post_images_path %>
</div>

app/views/post_images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post_image %>

<div>
  <%= link_to "Edit this post image", edit_post_image_path(@post_image) %> |
  <%= link_to "Back to post images", post_images_path %>

  <%= button_to "Destroy this post image", @post_image, method: :delete %>
</div>